### ISSUE TITLE
Request Status Code 400

### ISSUE THREAD

**Issue by 89z** [Davincible/goinsta#9] opened 2021-10-01 17:49 UTC
Using this code:

~~~go
package main

import (
   "github.com/Davincible/goinsta"
   "os"
)

func main() {
   insta := goinsta.New("srpen6", "PASSWORD")
   err := insta.Login()
   if err != nil {
      panic(err)
   }
   insta.ExportIO(os.Stdout)
}
~~~

I get this result:

~~~
Request Status Code 400: fail, Please wait a few minutes before you try again.
~~~

**Comment by Davincible** [comment] 2021-10-02 14:12
Do you always get this? Nothing special about the code snippet that should trigger it, apart from maybe running it too often.
You can add `insta.Debug = true` before calling login, and paste the output if you want to debug

**Comment by 89z** [comment] 2021-10-02 14:16
It outputs a bunch of garbage. If I had to guess, its because of this:

https://github.com/Davincible/goinsta/blob/172c4b597032ba02bc1bd4c51dd2fd5041b677b2/request.go#L179

**Comment by Davincible** [comment] 2021-10-02 14:24
But what is the endpoint that was called?

**Comment by 89z** [comment] 2021-10-02 14:28
~~~
Status code: 200 : launcher/sync/, 
Status code: 200 : launcher/sync/, 
Status code: 200 : zr/token/result/, 
Status code: 400 : accounts/login/, body: {"message":"Please wait a few minutes before you try again.","status":"fail","error_type":"rate_limit_error"},
Status code: 429 : accounts/contact_point_prefill/, body: {"message":"Please wait a few minutes before you try again.","status":"fail"},
Status code: 429 : accounts/get_prefill_candidates/, body: {"message":"Please wait a few minutes before you try again.","status":"fail"},
~~~

**Comment by 89z** [comment] 2021-10-02 14:33
Also, FYI you dont need to make 6 requests to log in. I took the code here and was able to trim it way, way down. It looks like you can do it in 2 requests or maybe even one:

https://github.com/89z/mech/tree/d2e7a8fd/research/2021-09-30

**Comment by Davincible** [comment] 2021-10-02 14:35
Hmm that's interesting. The last two don't matter, its the `accounts/login/` that shouldn't error. Because it does not seem to happen often my first guess would be that it could be something with your env. You can test it with a different account, VPNs or hook up your mobile hotspot to see if they give different results. 

About the request count, that is true, but I made goinsta to imitate the android app as closely as possible. Almost everycall the app makes when logging in, goinsta will make.

**Comment by 89z** [comment] 2021-10-02 14:37
> About the request count, that is true, but I made goinsta to imitate the android app as closely as possible. Almost everycall the app makes when logging in, goinsta will make.

I think that might be worth reconsidering, as I think that played was the cause of my current problems. The package should make as few requests as possible, as Instragram rate limits login requests.

**Comment by Davincible** [comment] 2021-10-02 14:41
It does, but only if you make a crazy amount of requests. It shouldn't hinder normal use. The prefill endpoints do quickly trigger, but they also do with the normal app. Login requests should be made sparingly, which is why it's important to save the cookies to disk, and reuse them.

If you think that is the cause of the issue you can vendor the library, and add sleep calls in this function: https://github.com/Davincible/goinsta/blob/172c4b597032ba02bc1bd4c51dd2fd5041b677b2/goinsta.go#L452

**Comment by 89z** [comment] 2021-10-02 14:47
I wasnt doing anything bad. All I did was take the code here, and as I was making some changes, I would run the login to test it. Towards the end of my code changes, I got locked out of my own account.

**Comment by Davincible** [comment] 2021-10-02 14:51
I'd try with another account, and/or another network (VPN, mobile hotspot), to rule out that that is or isn't the issue

**Comment by 89z** [comment] 2021-10-02 14:53
I dont have any other Instragram accounts. I tried to make another one now, but it seems the `user+2@gmail.com` trick doesnt work, so I tried using a `mailsac.com` email, but I never got the confirmation code. I also tried using my mobile network instead of ethernet, didnt work. I also tried `proxy.webshare.io`, didnt work.

**Comment by Davincible** [comment] 2021-10-02 14:57
You're allowed to make multiple accounts on one email/phone number, although they will be related then. I ended up making a few gmails to create test accounts

**Comment by 89z** [comment] 2021-10-02 15:00
I dont think so. I just tried it, and I get

~~~
Another account is using srpen6@gmail.com
~~~

**Comment by Davincible** [comment] 2021-10-02 15:04
If I in the app while being logged in on my main, go to profile > top left accounts drop down > add account > create new one > asks for username, this will be on your primary email

**Comment by 89z** [comment] 2021-10-02 15:08
I cant log into the website or app...

**Comment by Davincible** [comment] 2021-10-02 15:10
That sucks, then you know for sure its something to do with your account. Probably because you tried to log in too often. In the code snippet you posted you re-login every run, and if you even just run that 5 times in an hour it starts getting excessive. That's why the export function is useful

**Comment by Davincible** [comment] 2021-10-02 15:11
I'll close this issue for now, if you keep getting errors or have more questions feel free to post here or in the discussions tab

**Comment by 89z** [comment] 2021-10-02 15:12
Yes I know that. In ideal situation, I would export the tokens and not have to run the login code for many days or weeks. However I am not in that situation, as I need to run the login multiple times while testing my modifications to the code here.

**Closed by Davincible** 2021-10-02 15:11 UTC
